
[build-system]
requires = ["setuptools >= 77.0.3,<80"]
build-backend = "setuptools.build_meta"

[project]
name = "TracRpcProtocols"
version = "2.0.0"
authors = [
  { name="Olemis Lang", email="olemis+trac@gmail.com" },
]
description = """RPC protocols for Trac.

This project implements RPC protocols not provided by
TracXMLRPC plugin. This could be due to conflicting
dependencies, policies, or maybe other reasons. In the former
case this plugin MIGHT NOT install by default all the
dependencies needed by every protocol implementation. In that
case it will check whether dependencies are available or not
and will display informative messages if it is not possible
to process client requests.

Copyright 2010 Olemis Lang <olemis at gmail.com>
Licensed under the Apache version 2 License
"""
readme = "README"
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Plugins", 
  "Environment :: Web Environment", 
  "Framework :: Trac", 
  "Intended Audience :: Developers", 
  "Intended Audience :: Information Technology", 
  "Intended Audience :: Other Audience", 
  "Intended Audience :: System Administrators", 
  "Natural Language :: English", 
  "Natural Language :: Spanish", 
  "Operating System :: OS Independent", 
  "Programming Language :: Python", 
  "Programming Language :: Python :: 2.5", 
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: CGI Tools/Libraries", 
  "Topic :: Internet :: WWW/HTTP :: HTTP Servers", 
  "Topic :: Internet :: WWW/HTTP :: WSGI", 
  "Topic :: Software Development :: Bug Tracking", 
  "Topic :: Software Development :: Libraries :: Application Frameworks", 
  "Topic :: Software Development :: Libraries :: Python Modules", 
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://trac-hacks.org/wiki/TracRpcProtocolsPlugin"
Issues = "https://github.com/pypa/sampleproject/issues"
Sourceforge = "https://sourceforge.net/p/makercitos/trac-rpcext/"
Github = "https://github.com/olemislang/trac-rpcext"
PyPI = "https://pypi.org/project/TracRpcProtocols"

[project.entry-points."trac.plugins"]
amf     = "tracrpcext._amf"
hessian = "tracrpcext._hessian"

